### ISSUE TITLE
Load system roles at startup

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/hooghlycommerce#2]
Check if the roles - ADMIN, USER are present at startup.
If not present create those two roles. 

Tip : Use Spring BOOT Command line runner. User Order annotation to ensure that this command line runner is executed before the default user creation command line runner #1.

**Comment by kdhrubo** [comment]
The orderflow system has two roles ADMIN, USER. 
Following classes will be created
1> RoleLoaderCommandLineRunner -- Spring Command Line runner
2> RoleRepository --- Spring DATA Repository class
3> Role - JPA Entity class.

**Comment by kdhrubo** [comment]
To automatically create the table use 
jpa:
    hibernate:
      ddl-auto: update

In the application.yml file. Check the commerce project for example.

**Comment by Rajiv-mar121** [comment]
Roles created if not available .
code pushed please review once.
feature/02_roles
