### ISSUE TITLE
As an admin user I want to login to orderflow home page after authentication

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/hooghlycommerce#46]

**Comment by Rajiv-mar121** [comment]
login to orderflow home page after authentication .
authentication where we will do ?
Do you mean.. as we launch oderflow it shud prompt login page later if successful another home page must be laid out ?

**Comment by kdhrubo** [comment]
Authentication will be done by Spring Security. You can refer to CRX project for setup.
Yes when you launch orderflow it takes you to login page and then on successful authentication home page is displayed.

**Comment by Rajiv-mar121** [comment]
This feature has been accomplished.
Branch: feature/46_ui_page
