### ISSUE TITLE
Convert Lead form 

### ISSUE THREAD

**Issue by Rajiv-mar121** [kdhrubo/hooghlycommerce#66]
Convert by using tab <ul class="nav nav-tabs"></ul> pane <nav>  
==============
    <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
    <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>

==============
<ul class="nav nav-tabs">
  </ul>
https://v4-alpha.getbootstrap.com/components/navs/

https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_tab&stacked=h

**Comment by kdhrubo** [comment]
@Rajiv-mar121 this issue should be logged in HooghlyCRM
